# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='english',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='foreign',
            field=models.CharField(default='ni hao', max_length=100),
            preserve_default=False,
        ),
    ]
