# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_bucket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='last_reviewed',
            field=models.DateTimeField(null=True),
        ),
    ]
