# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 05:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0009_auto_20170612_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_reviewed', models.DateTimeField(null=True)),
                ('times_right', models.IntegerField(default=0)),
                ('know_status', models.IntegerField(default=0)),
                ('bucket', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='review.Bucket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='bucket',
        ),
        migrations.RemoveField(
            model_name='word',
            name='know_status',
        ),
        migrations.RemoveField(
            model_name='word',
            name='last_reviewed',
        ),
        migrations.RemoveField(
            model_name='word',
            name='times_right',
        ),
        migrations.AddField(
            model_name='wordstats',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_stats', to='review.Word'),
        ),
    ]
