# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_auto_20170625_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='user',
        ),
    ]
